name: Update submodules

on:
  schedule:
    - cron: '0 6,18 * * *'
  workflow_dispatch:

permissions:
  content: write

jobs:
  update:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Configurar git
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

        - name: Actualizar submodulos a sus ramas remotas configuradas
          run: |
            git submodule update --init --remote --recursive

        - name: Commit y push solo si hay cambios
          run: |
            git add -A
            if git diff --cached --quiet; then
              echo "No hay actualizaciones de submódulos."
            else
              git commit -m "Auto-update submodules: $(date -u +'%Y-%m-%d %H:%M UTC') [skip ci]"
              git push
            fi
